//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESENT_BankCity
    {
        public SESENT_BankCity()
        {
            this.SESENT_BankLineNumber = new HashSet<SESENT_BankLineNumber>();
        }
    
        public int Provinceid { get; set; }
        public string Province { get; set; }
        public string Property1 { get; set; }
    
        public virtual ICollection<SESENT_BankLineNumber> SESENT_BankLineNumber { get; set; }
    }
}
