//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESENT_MessageText
    {
        public int Id { get; set; }
        public string SendID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public short Type { get; set; }
        public string Recld { get; set; }
        public decimal Gift { get; set; }
        public bool HasGift { get; set; }
    }
}
