//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESENT_USERS
    {
        public SESENT_USERS()
        {
            this.userName = "迷彩玩家";
            this.userPwd = "123456";
            this.UseAmount = 0m;
            this.userType = 0;
            this.userPayPwd = "654321";
            this.AgentMoney = 0m;
        }
    
        public string userName { get; set; }
        public string userPwd { get; set; }
        public string Phone { get; set; }
        public decimal UseAmount { get; set; }
        public short userType { get; set; }
        public string userPayPwd { get; set; }
        public string SuperiorAgent { get; set; }
        public decimal AgentMoney { get; set; }
        public string AccountID { get; set; }
        public int ID { get; set; }
        public short Lv { get; set; }
        public decimal Recharge { get; set; }
        public string Consumption { get; set; }
    }
}
