//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESENT_BasketBallMatch
    {
        public long BasketballID { get; set; }
        public string No { get; set; }
        public string Match { get; set; }
        public string EndTime { get; set; }
        public string MainteamRanking { get; set; }
        public string Mainteam { get; set; }
        public string Visitingteam { get; set; }
        public string VisitingteamRanking { get; set; }
        public System.DateTime MatchDate { get; set; }
        public string MatchWeek { get; set; }
        public string Fk_FnID { get; set; }
    }
}
