//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESENT_CashCard
    {
        public int Id { get; set; }
        public string AccountID { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public string LineNumber { get; set; }
        public string NetSite { get; set; }
        public string BankNumber { get; set; }
        public System.DateTime EnterTime { get; set; }
    }
}
