//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESENT_RankingSystemSetting
    {
        public int Id { get; set; }
        public short Lv { get; set; }
        public decimal Recharge { get; set; }
        public decimal Consumption { get; set; }
        public short Reward { get; set; }
        public decimal UpgradeAward { get; set; }
        public decimal InsuredAmount { get; set; }
    }
}
