//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESENT_GenDan
    {
        public int Id { get; set; }
        public string AccountID { get; set; }
        public string CreateDateTime { get; set; }
        public string GameType { get; set; }
        public string GameID { get; set; }
        public string EndTime { get; set; }
        public Nullable<short> Status { get; set; }
        public decimal BeginMoney { get; set; }
    }
}
